// Payphone's return leg. This route replaces the Stripe webhook, and it is worth being
// explicit that it is a *weaker* mechanism, because the difference drives every decision
// below: Stripe pushed a signed event and retried it for days, whereas Payphone redirects
// the buyer's browser here with two query parameters and expects us to pull the truth back
// ourselves. There is no signature. The parameters prove nothing. Only the confirm
// response is authoritative.
//
// And it is on a clock: an approved payment that is not confirmed within five minutes is
// reversed automatically by Payphone. That is a safe failure — the buyer gets their money
// back — but it means fulfilment happens here, synchronously, or not at all.
//
// Why an API route rather than doing this inside the order page: `[lang]/order/[id].astro`
// documents that it reads status from Mongo and never from redirect parameters, and it is
// reachable from a link, a refresh, an email and the account history. Making it fulfil
// would invert the exact property that comment exists to protect, and would run
// token-minting on every one of those visits.
import type { APIRoute } from 'astro';
import { createEmailer, getDbConfig, getDownloadConfig, getPayphoneConfig, getPublicSiteUrl } from '../../lib/config';
import { getDb } from '../../lib/db';
import { fulfilOrder } from '../../lib/fulfilment';
import type { Locale } from '../../lib/i18n';
import { getOrderById, type OrderDoc } from '../../lib/orders';
import { claimConfirm, findPaymentAttempt, recordConfirmResponse, type PayphoneTransactionDoc } from '../../lib/payments';
import { confirmPayphonePayment, PAYPHONE_STATUS_APPROVED, PAYPHONE_STATUS_CANCELED, type PayphoneConfirmResponse } from '../../lib/payphone';

export const prerender = false;

/** Appended to the order URL so the buyer is told *something* went wrong. This does not
 *  violate the order page's don't-trust-the-redirect rule: the parameter selects a
 *  message, while the order's actual status still comes from Mongo. */
type PaymentOutcome = 'declined' | 'unconfirmed';

export const GET: APIRoute = async ({ url, redirect }) => {
  const clientTransactionId = url.searchParams.get('clientTransactionId')?.trim();
  const rawId = url.searchParams.get('id')?.trim();

  // A request that does not carry both parameters was not generated by Payphone, and
  // there is no order it could sensibly be redirected to.
  if (!clientTransactionId || !rawId || !/^\d+$/.test(rawId)) {
    return new Response('Missing or malformed id / clientTransactionId', { status: 400 });
  }
  const payphoneTransactionId = Number(rawId);

  const db = await getDb(getDbConfig());

  // Lookup and claim in one atomic step. A null here means someone else owns the confirm
  // or already ran it — two tabs racing, or the buyer refreshing a return URL that already
  // worked. Either way this request must NOT call Payphone: confirm is terminal, so a
  // second call is not a harmless duplicate, it is an error that reads like a decline.
  const claimed = await claimConfirm(db, clientTransactionId, payphoneTransactionId);
  if (!claimed) {
    const existing = await findPaymentAttempt(db, clientTransactionId);
    if (!existing) {
      return new Response('Unknown transaction', { status: 404 });
    }
    // Re-derived from what was recorded, so a buyer who refreshes after a failed payment
    // sees the same explanation they saw the first time instead of an unexplained pending
    // order. A confirm still in flight (no record yet) gets no message rather than a
    // guessed one.
    return redirect(orderUrl(existing, outcomeOf(existing)), 302);
  }

  const result = await confirmPayphonePayment(getPayphoneConfig().token, {
    id: payphoneTransactionId,
    clientTxId: clientTransactionId,
  });

  // Persisted BEFORE anything is done with it, and this ordering is the most important
  // line in the file. A crash between the confirm succeeding and the order being marked
  // paid means money was taken and nothing was delivered — with no webhook to retry it.
  // Writing the response down first turns that from invisible into something the admin
  // reconciliation view can see and the reconcile script can finish. Everything after this
  // point is re-runnable; this is not.
  await recordConfirmResponse(db, claimed._id, {
    ok: result.ok,
    httpStatus: result.httpStatus,
    at: new Date(),
    body: result.body,
  });

  const order = await getOrderById(db, claimed.orderId);
  if (!order) {
    console.error('payphone-confirm: attempt references a missing order', clientTransactionId, claimed.orderId.toString());
    return redirect(orderUrl(claimed, 'unconfirmed'), 302);
  }

  const verdict = evaluateConfirm(result, clientTransactionId, payphoneTransactionId, order);
  if (verdict.outcome) {
    console.error(`payphone-confirm: ${verdict.reason}`, clientTransactionId);
    return redirect(orderUrl(claimed, verdict.outcome), 302);
  }

  try {
    await fulfil(db, order, verdict.body, claimed.lang);
  } catch (err) {
    // The payment is real and already recorded, so the buyer still goes to their order
    // page — where the status will read `paid` if markOrderPaid landed before the failure.
    // Reconciliation is what closes the gap; failing the redirect would only strand them.
    console.error('payphone-confirm: fulfilment failed after a confirmed payment', clientTransactionId, err);
  }

  return redirect(orderUrl(claimed), 302);
};

/** The locale comes from the stored attempt, never from a query parameter — Payphone's
 *  response URL is one static URL with no locale in it, so this is the only trustworthy
 *  source. */
function orderUrl(attempt: PayphoneTransactionDoc, outcome?: PaymentOutcome): string {
  const base = `/${attempt.lang}/order/${attempt.orderId.toString()}`;
  return outcome ? `${base}?payment=${outcome}` : base;
}

/** The outcome already on record for an attempt this request did not get to confirm. */
function outcomeOf(attempt: PayphoneTransactionDoc): PaymentOutcome | undefined {
  if (!attempt.confirm) return undefined;
  const statusCode = (attempt.confirm.body as PayphoneConfirmResponse).statusCode;
  if (attempt.confirm.ok && statusCode === PAYPHONE_STATUS_APPROVED) return undefined;
  return statusCode === PAYPHONE_STATUS_CANCELED ? 'declined' : 'unconfirmed';
}

type Verdict =
  | { outcome: null; body: PayphoneConfirmResponse }
  | { outcome: PaymentOutcome; reason: string };

/**
 * Everything that has to be true before an order is treated as paid.
 *
 * The amount check is the security boundary, and it is the reason this is a separate
 * function rather than a chain of ifs inline: `id` and `clientTransactionId` arrive from a
 * query string that anyone can type, so the confirm response is the only statement about
 * what was actually paid that can be trusted — and an approval for the wrong amount is not
 * an approval for this order.
 *
 * A mismatch is deliberately reported to the buyer as the same generic `unconfirmed` as a
 * network failure. It is a fraud signal; it belongs in the logs and the admin panel, not
 * in a distinct string an attacker can probe for.
 */
function evaluateConfirm(
  result: Awaited<ReturnType<typeof confirmPayphonePayment>>,
  clientTransactionId: string,
  payphoneTransactionId: number,
  order: OrderDoc,
): Verdict {
  if (!result.ok) {
    const err = result.body as { message?: string; errorCode?: number };
    return { outcome: 'unconfirmed', reason: `confirm failed (HTTP ${result.httpStatus}, code ${err.errorCode ?? '-'}): ${err.message ?? ''}` };
  }

  const body = result.body;
  if (body.clientTransactionId !== clientTransactionId || body.transactionId !== payphoneTransactionId) {
    return { outcome: 'unconfirmed', reason: 'confirm response identifies a different transaction' };
  }
  if (body.statusCode === PAYPHONE_STATUS_CANCELED) {
    return { outcome: 'declined', reason: 'payment cancelled by the buyer or the issuer' };
  }
  if (body.statusCode !== PAYPHONE_STATUS_APPROVED) {
    return { outcome: 'unconfirmed', reason: `unexpected statusCode ${body.statusCode}` };
  }
  if (body.amount !== order.totalCents) {
    return { outcome: 'unconfirmed', reason: `amount mismatch: gateway says ${body.amount}, order is ${order.totalCents}` };
  }

  return { outcome: null, body };
}

/**
 * Marks the order paid, mints one download token per item, and emails the links.
 *
 * The body of this moved to lib/fulfilment.ts when bank transfers arrived: an order
 * approved by hand in the admin panel has to deliver exactly what a card payment delivers,
 * and the only way to be sure of that is for both to run the same code. What stays here is
 * the part that is genuinely Payphone's — translating a confirm response into the
 * provider-neutral `OrderPayment` the rest of the app reads.
 */
async function fulfil(
  db: Awaited<ReturnType<typeof getDb>>,
  order: OrderDoc,
  body: PayphoneConfirmResponse,
  lang: Locale,
): Promise<void> {
  const downloadConfig = getDownloadConfig();

  await fulfilOrder(db, {
    order,
    actor: 'payphone-confirm',
    lang,
    payment: {
      method: 'payphone',
      transactionId: String(body.transactionId),
      authorizationCode: body.authorizationCode,
      cardBrand: body.cardBrand,
      lastDigits: body.lastDigits,
      document: body.document,
    },
    // The gateway's email wins when it has one, exactly as Stripe's billing email did.
    // When it doesn't, the address collected on the checkout page is already on the order.
    ...(body.email ? { customer: { email: body.email, name: order.customer.name } } : {}),
    siteUrl: getPublicSiteUrl(),
    ttlDays: downloadConfig.ttlDays,
    maxUses: downloadConfig.maxUses,
    // Passed uncalled on purpose — see `emailer` in FulfilOrderParams.
    emailer: createEmailer,
  });
}
